### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by tombh** [coltmeister/bitnami-postgis#2]
Just wanted to say thank you for this. It really helped me out. I've got it running against the Postgres Helm chart tweaking to the latest v11 Postgres. I don't want to turn this into an issue, because it's not at all a problem, but a nice to have would be one of those Dockerfile multistage builds so the all the build dependencies are excluded. But anyway, this was so useful for me, thanks again.

**Comment by coltondotio** [comment]
Hey Tom, sorry for the delayed response. Glad you found this to be useful!
